version: '3.2'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start